-- Generated Customizations

-- Customizations for ITEM_MP_001
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_001_SPICE', 'ITEM_MP_001', 'Spice Level', 'single', 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_SPICE_MILD', 'CG_MP_001_SPICE', 'Mild', 0.00, 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_SPICE_SPICY', 'CG_MP_001_SPICE', 'Spicy (harissa instead of hot honey)', 0.00, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_001_REMOVE', 'ITEM_MP_001', 'Remove Items', 'multiple', 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_REMOVE_CHEESE', 'CG_MP_001_REMOVE', 'No cheese', 0.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_REMOVE_GARLIC', 'CG_MP_001_REMOVE', 'No garlic', 0.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_REMOVE_SALAD', 'CG_MP_001_REMOVE', 'No salad (fries only)', 0.00, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_REMOVE_HONEY', 'CG_MP_001_REMOVE', 'No hot honey', 0.00, 0, 4);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_001_ADDON', 'ITEM_MP_001', 'Add-ons', 'multiple', 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_ADDON_CHICKEN', 'CG_MP_001_ADDON', 'Chicken topping on fries', 3.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_ADDON_BRISKET', 'CG_MP_001_ADDON', 'Brisket topping on fries', 4.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_ADDON_MIXED', 'CG_MP_001_ADDON', 'Mixed topping on fries', 5.00, 0, 3);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_001_EXTRA', 'ITEM_MP_001', 'Extras', 'multiple', 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_EXTRA_HALLOUMI', 'CG_MP_001_EXTRA', 'Grilled Halloumi Sticks', 6.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_EXTRA_POPPERS', 'CG_MP_001_EXTRA', 'Cheesy Pizza Poppers', 6.50, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_001_DRINK', 'ITEM_MP_001', 'Add a Drink', 'single', 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_DRINK_1', 'CG_MP_001_DRINK', 'Shani Can 330ml', 2.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_DRINK_2', 'CG_MP_001_DRINK', 'Rubicon Guava Can 330ml', 2.50, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_DRINK_3', 'CG_MP_001_DRINK', 'Rubicon Mango Can 330ml', 2.50, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_DRINK_4', 'CG_MP_001_DRINK', 'Rubicon Passion Fruit Can 330ml', 2.50, 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_DRINK_5', 'CG_MP_001_DRINK', 'Palestine Cola Can 330ml', 2.50, 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_DRINK_6', 'CG_MP_001_DRINK', 'Palestine Cola (Sugar Free) Can 330ml', 2.50, 0, 6);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_DRINK_7', 'CG_MP_001_DRINK', 'Palestine Lemon and Lime Can 330ml', 2.50, 0, 7);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_DRINK_8', 'CG_MP_001_DRINK', 'Palestine Orange Can 330ml', 2.50, 0, 8);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_DRINK_9', 'CG_MP_001_DRINK', 'Bottled Water 350ml', 2.50, 0, 9);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_001_DRINK_10', 'CG_MP_001_DRINK', 'Capri Sun 350ml', 2.00, 0, 10);

-- Customizations for ITEM_MP_002
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_002_SPICE', 'ITEM_MP_002', 'Spice Level', 'single', 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_SPICE_MILD', 'CG_MP_002_SPICE', 'Mild', 0.00, 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_SPICE_SPICY', 'CG_MP_002_SPICE', 'Spicy (harissa instead of hot honey)', 0.00, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_002_REMOVE', 'ITEM_MP_002', 'Remove Items', 'multiple', 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_REMOVE_CHEESE', 'CG_MP_002_REMOVE', 'No cheese', 0.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_REMOVE_GARLIC', 'CG_MP_002_REMOVE', 'No garlic', 0.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_REMOVE_SALAD', 'CG_MP_002_REMOVE', 'No salad (fries only)', 0.00, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_REMOVE_HONEY', 'CG_MP_002_REMOVE', 'No hot honey', 0.00, 0, 4);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_002_ADDON', 'ITEM_MP_002', 'Add-ons', 'multiple', 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_ADDON_CHICKEN', 'CG_MP_002_ADDON', 'Chicken topping on fries', 3.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_ADDON_BRISKET', 'CG_MP_002_ADDON', 'Brisket topping on fries', 4.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_ADDON_MIXED', 'CG_MP_002_ADDON', 'Mixed topping on fries', 5.00, 0, 3);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_002_EXTRA', 'ITEM_MP_002', 'Extras', 'multiple', 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_EXTRA_HALLOUMI', 'CG_MP_002_EXTRA', 'Grilled Halloumi Sticks', 6.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_EXTRA_POPPERS', 'CG_MP_002_EXTRA', 'Cheesy Pizza Poppers', 6.50, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_002_DRINK', 'ITEM_MP_002', 'Add a Drink', 'single', 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_DRINK_1', 'CG_MP_002_DRINK', 'Shani Can 330ml', 2.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_DRINK_2', 'CG_MP_002_DRINK', 'Rubicon Guava Can 330ml', 2.50, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_DRINK_3', 'CG_MP_002_DRINK', 'Rubicon Mango Can 330ml', 2.50, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_DRINK_4', 'CG_MP_002_DRINK', 'Rubicon Passion Fruit Can 330ml', 2.50, 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_DRINK_5', 'CG_MP_002_DRINK', 'Palestine Cola Can 330ml', 2.50, 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_DRINK_6', 'CG_MP_002_DRINK', 'Palestine Cola (Sugar Free) Can 330ml', 2.50, 0, 6);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_DRINK_7', 'CG_MP_002_DRINK', 'Palestine Lemon and Lime Can 330ml', 2.50, 0, 7);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_DRINK_8', 'CG_MP_002_DRINK', 'Palestine Orange Can 330ml', 2.50, 0, 8);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_DRINK_9', 'CG_MP_002_DRINK', 'Bottled Water 350ml', 2.50, 0, 9);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_002_DRINK_10', 'CG_MP_002_DRINK', 'Capri Sun 350ml', 2.00, 0, 10);

-- Customizations for ITEM_MP_003
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_003_SPICE', 'ITEM_MP_003', 'Spice Level', 'single', 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_SPICE_MILD', 'CG_MP_003_SPICE', 'Mild', 0.00, 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_SPICE_SPICY', 'CG_MP_003_SPICE', 'Spicy (harissa instead of hot honey)', 0.00, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_003_REMOVE', 'ITEM_MP_003', 'Remove Items', 'multiple', 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_REMOVE_CHEESE', 'CG_MP_003_REMOVE', 'No cheese', 0.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_REMOVE_GARLIC', 'CG_MP_003_REMOVE', 'No garlic', 0.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_REMOVE_SALAD', 'CG_MP_003_REMOVE', 'No salad (fries only)', 0.00, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_REMOVE_HONEY', 'CG_MP_003_REMOVE', 'No hot honey', 0.00, 0, 4);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_003_ADDON', 'ITEM_MP_003', 'Add-ons', 'multiple', 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_ADDON_CHICKEN', 'CG_MP_003_ADDON', 'Chicken topping on fries', 3.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_ADDON_BRISKET', 'CG_MP_003_ADDON', 'Brisket topping on fries', 4.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_ADDON_MIXED', 'CG_MP_003_ADDON', 'Mixed topping on fries', 5.00, 0, 3);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_003_EXTRA', 'ITEM_MP_003', 'Extras', 'multiple', 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_EXTRA_HALLOUMI', 'CG_MP_003_EXTRA', 'Grilled Halloumi Sticks', 6.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_EXTRA_POPPERS', 'CG_MP_003_EXTRA', 'Cheesy Pizza Poppers', 6.50, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_003_DRINK', 'ITEM_MP_003', 'Add a Drink', 'single', 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_DRINK_1', 'CG_MP_003_DRINK', 'Shani Can 330ml', 2.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_DRINK_2', 'CG_MP_003_DRINK', 'Rubicon Guava Can 330ml', 2.50, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_DRINK_3', 'CG_MP_003_DRINK', 'Rubicon Mango Can 330ml', 2.50, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_DRINK_4', 'CG_MP_003_DRINK', 'Rubicon Passion Fruit Can 330ml', 2.50, 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_DRINK_5', 'CG_MP_003_DRINK', 'Palestine Cola Can 330ml', 2.50, 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_DRINK_6', 'CG_MP_003_DRINK', 'Palestine Cola (Sugar Free) Can 330ml', 2.50, 0, 6);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_DRINK_7', 'CG_MP_003_DRINK', 'Palestine Lemon and Lime Can 330ml', 2.50, 0, 7);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_DRINK_8', 'CG_MP_003_DRINK', 'Palestine Orange Can 330ml', 2.50, 0, 8);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_DRINK_9', 'CG_MP_003_DRINK', 'Bottled Water 350ml', 2.50, 0, 9);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_003_DRINK_10', 'CG_MP_003_DRINK', 'Capri Sun 350ml', 2.00, 0, 10);

-- Customizations for ITEM_MP_004
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_004_SPICE', 'ITEM_MP_004', 'Spice Level', 'single', 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_SPICE_MILD', 'CG_MP_004_SPICE', 'Mild', 0.00, 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_SPICE_SPICY', 'CG_MP_004_SPICE', 'Spicy (harissa instead of hot honey)', 0.00, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_004_REMOVE', 'ITEM_MP_004', 'Remove Items', 'multiple', 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_REMOVE_CHEESE', 'CG_MP_004_REMOVE', 'No cheese', 0.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_REMOVE_GARLIC', 'CG_MP_004_REMOVE', 'No garlic', 0.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_REMOVE_SALAD', 'CG_MP_004_REMOVE', 'No salad (fries only)', 0.00, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_REMOVE_HONEY', 'CG_MP_004_REMOVE', 'No hot honey', 0.00, 0, 4);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_004_ADDON', 'ITEM_MP_004', 'Add-ons', 'multiple', 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_ADDON_CHICKEN', 'CG_MP_004_ADDON', 'Chicken topping on fries', 3.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_ADDON_BRISKET', 'CG_MP_004_ADDON', 'Brisket topping on fries', 4.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_ADDON_MIXED', 'CG_MP_004_ADDON', 'Mixed topping on fries', 5.00, 0, 3);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_004_EXTRA', 'ITEM_MP_004', 'Extras', 'multiple', 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_EXTRA_HALLOUMI', 'CG_MP_004_EXTRA', 'Grilled Halloumi Sticks', 6.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_EXTRA_POPPERS', 'CG_MP_004_EXTRA', 'Cheesy Pizza Poppers', 6.50, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_MP_004_DRINK', 'ITEM_MP_004', 'Add a Drink', 'single', 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_DRINK_1', 'CG_MP_004_DRINK', 'Shani Can 330ml', 2.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_DRINK_2', 'CG_MP_004_DRINK', 'Rubicon Guava Can 330ml', 2.50, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_DRINK_3', 'CG_MP_004_DRINK', 'Rubicon Mango Can 330ml', 2.50, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_DRINK_4', 'CG_MP_004_DRINK', 'Rubicon Passion Fruit Can 330ml', 2.50, 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_DRINK_5', 'CG_MP_004_DRINK', 'Palestine Cola Can 330ml', 2.50, 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_DRINK_6', 'CG_MP_004_DRINK', 'Palestine Cola (Sugar Free) Can 330ml', 2.50, 0, 6);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_DRINK_7', 'CG_MP_004_DRINK', 'Palestine Lemon and Lime Can 330ml', 2.50, 0, 7);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_DRINK_8', 'CG_MP_004_DRINK', 'Palestine Orange Can 330ml', 2.50, 0, 8);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_DRINK_9', 'CG_MP_004_DRINK', 'Bottled Water 350ml', 2.50, 0, 9);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_MP_004_DRINK_10', 'CG_MP_004_DRINK', 'Capri Sun 350ml', 2.00, 0, 10);

-- Customizations for ITEM_SW_001
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_SW_001_SPICE', 'ITEM_SW_001', 'Spice Level', 'single', 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_SPICE_MILD', 'CG_SW_001_SPICE', 'Mild', 0.00, 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_SPICE_SPICY', 'CG_SW_001_SPICE', 'Spicy (harissa instead of hot honey)', 0.00, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_SW_001_REMOVE', 'ITEM_SW_001', 'Remove Items', 'multiple', 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_REMOVE_CHEESE', 'CG_SW_001_REMOVE', 'No cheese', 0.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_REMOVE_GARLIC', 'CG_SW_001_REMOVE', 'No garlic', 0.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_REMOVE_SALAD', 'CG_SW_001_REMOVE', 'No salad (fries only)', 0.00, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_REMOVE_HONEY', 'CG_SW_001_REMOVE', 'No hot honey', 0.00, 0, 4);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_SW_001_ADDON', 'ITEM_SW_001', 'Add-ons', 'multiple', 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_ADDON_CHICKEN', 'CG_SW_001_ADDON', 'Chicken topping on fries', 3.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_ADDON_BRISKET', 'CG_SW_001_ADDON', 'Brisket topping on fries', 4.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_ADDON_MIXED', 'CG_SW_001_ADDON', 'Mixed topping on fries', 5.00, 0, 3);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_SW_001_EXTRA', 'ITEM_SW_001', 'Extras', 'multiple', 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_EXTRA_HALLOUMI', 'CG_SW_001_EXTRA', 'Grilled Halloumi Sticks', 6.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_EXTRA_POPPERS', 'CG_SW_001_EXTRA', 'Cheesy Pizza Poppers', 6.50, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_SW_001_DRINK', 'ITEM_SW_001', 'Add a Drink', 'single', 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_DRINK_1', 'CG_SW_001_DRINK', 'Shani Can 330ml', 2.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_DRINK_2', 'CG_SW_001_DRINK', 'Rubicon Guava Can 330ml', 2.50, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_DRINK_3', 'CG_SW_001_DRINK', 'Rubicon Mango Can 330ml', 2.50, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_DRINK_4', 'CG_SW_001_DRINK', 'Rubicon Passion Fruit Can 330ml', 2.50, 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_DRINK_5', 'CG_SW_001_DRINK', 'Palestine Cola Can 330ml', 2.50, 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_DRINK_6', 'CG_SW_001_DRINK', 'Palestine Cola (Sugar Free) Can 330ml', 2.50, 0, 6);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_DRINK_7', 'CG_SW_001_DRINK', 'Palestine Lemon and Lime Can 330ml', 2.50, 0, 7);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_DRINK_8', 'CG_SW_001_DRINK', 'Palestine Orange Can 330ml', 2.50, 0, 8);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_DRINK_9', 'CG_SW_001_DRINK', 'Bottled Water 350ml', 2.50, 0, 9);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_001_DRINK_10', 'CG_SW_001_DRINK', 'Capri Sun 350ml', 2.00, 0, 10);

-- Customizations for ITEM_SW_002
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_SW_002_SPICE', 'ITEM_SW_002', 'Spice Level', 'single', 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_SPICE_MILD', 'CG_SW_002_SPICE', 'Mild', 0.00, 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_SPICE_SPICY', 'CG_SW_002_SPICE', 'Spicy (harissa instead of hot honey)', 0.00, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_SW_002_REMOVE', 'ITEM_SW_002', 'Remove Items', 'multiple', 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_REMOVE_CHEESE', 'CG_SW_002_REMOVE', 'No cheese', 0.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_REMOVE_GARLIC', 'CG_SW_002_REMOVE', 'No garlic', 0.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_REMOVE_SALAD', 'CG_SW_002_REMOVE', 'No salad (fries only)', 0.00, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_REMOVE_HONEY', 'CG_SW_002_REMOVE', 'No hot honey', 0.00, 0, 4);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_SW_002_ADDON', 'ITEM_SW_002', 'Add-ons', 'multiple', 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_ADDON_CHICKEN', 'CG_SW_002_ADDON', 'Chicken topping on fries', 3.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_ADDON_BRISKET', 'CG_SW_002_ADDON', 'Brisket topping on fries', 4.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_ADDON_MIXED', 'CG_SW_002_ADDON', 'Mixed topping on fries', 5.00, 0, 3);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_SW_002_EXTRA', 'ITEM_SW_002', 'Extras', 'multiple', 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_EXTRA_HALLOUMI', 'CG_SW_002_EXTRA', 'Grilled Halloumi Sticks', 6.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_EXTRA_POPPERS', 'CG_SW_002_EXTRA', 'Cheesy Pizza Poppers', 6.50, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_SW_002_DRINK', 'ITEM_SW_002', 'Add a Drink', 'single', 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_DRINK_1', 'CG_SW_002_DRINK', 'Shani Can 330ml', 2.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_DRINK_2', 'CG_SW_002_DRINK', 'Rubicon Guava Can 330ml', 2.50, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_DRINK_3', 'CG_SW_002_DRINK', 'Rubicon Mango Can 330ml', 2.50, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_DRINK_4', 'CG_SW_002_DRINK', 'Rubicon Passion Fruit Can 330ml', 2.50, 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_DRINK_5', 'CG_SW_002_DRINK', 'Palestine Cola Can 330ml', 2.50, 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_DRINK_6', 'CG_SW_002_DRINK', 'Palestine Cola (Sugar Free) Can 330ml', 2.50, 0, 6);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_DRINK_7', 'CG_SW_002_DRINK', 'Palestine Lemon and Lime Can 330ml', 2.50, 0, 7);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_DRINK_8', 'CG_SW_002_DRINK', 'Palestine Orange Can 330ml', 2.50, 0, 8);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_DRINK_9', 'CG_SW_002_DRINK', 'Bottled Water 350ml', 2.50, 0, 9);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_002_DRINK_10', 'CG_SW_002_DRINK', 'Capri Sun 350ml', 2.00, 0, 10);

-- Customizations for ITEM_SW_003
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_SW_003_SPICE', 'ITEM_SW_003', 'Spice Level', 'single', 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_SPICE_MILD', 'CG_SW_003_SPICE', 'Mild', 0.00, 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_SPICE_SPICY', 'CG_SW_003_SPICE', 'Spicy (harissa instead of hot honey)', 0.00, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_SW_003_REMOVE', 'ITEM_SW_003', 'Remove Items', 'multiple', 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_REMOVE_CHEESE', 'CG_SW_003_REMOVE', 'No cheese', 0.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_REMOVE_GARLIC', 'CG_SW_003_REMOVE', 'No garlic', 0.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_REMOVE_SALAD', 'CG_SW_003_REMOVE', 'No salad (fries only)', 0.00, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_REMOVE_HONEY', 'CG_SW_003_REMOVE', 'No hot honey', 0.00, 0, 4);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_SW_003_ADDON', 'ITEM_SW_003', 'Add-ons', 'multiple', 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_ADDON_CHICKEN', 'CG_SW_003_ADDON', 'Chicken topping on fries', 3.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_ADDON_BRISKET', 'CG_SW_003_ADDON', 'Brisket topping on fries', 4.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_ADDON_MIXED', 'CG_SW_003_ADDON', 'Mixed topping on fries', 5.00, 0, 3);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_SW_003_EXTRA', 'ITEM_SW_003', 'Extras', 'multiple', 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_EXTRA_HALLOUMI', 'CG_SW_003_EXTRA', 'Grilled Halloumi Sticks', 6.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_EXTRA_POPPERS', 'CG_SW_003_EXTRA', 'Cheesy Pizza Poppers', 6.50, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_SW_003_DRINK', 'ITEM_SW_003', 'Add a Drink', 'single', 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_DRINK_1', 'CG_SW_003_DRINK', 'Shani Can 330ml', 2.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_DRINK_2', 'CG_SW_003_DRINK', 'Rubicon Guava Can 330ml', 2.50, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_DRINK_3', 'CG_SW_003_DRINK', 'Rubicon Mango Can 330ml', 2.50, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_DRINK_4', 'CG_SW_003_DRINK', 'Rubicon Passion Fruit Can 330ml', 2.50, 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_DRINK_5', 'CG_SW_003_DRINK', 'Palestine Cola Can 330ml', 2.50, 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_DRINK_6', 'CG_SW_003_DRINK', 'Palestine Cola (Sugar Free) Can 330ml', 2.50, 0, 6);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_DRINK_7', 'CG_SW_003_DRINK', 'Palestine Lemon and Lime Can 330ml', 2.50, 0, 7);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_DRINK_8', 'CG_SW_003_DRINK', 'Palestine Orange Can 330ml', 2.50, 0, 8);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_DRINK_9', 'CG_SW_003_DRINK', 'Bottled Water 350ml', 2.50, 0, 9);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_SW_003_DRINK_10', 'CG_SW_003_DRINK', 'Capri Sun 350ml', 2.00, 0, 10);

-- Customizations for ITEM_LF_001
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_LF_001_SPICE', 'ITEM_LF_001', 'Spice Level', 'single', 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_SPICE_MILD', 'CG_LF_001_SPICE', 'Mild', 0.00, 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_SPICE_SPICY', 'CG_LF_001_SPICE', 'Spicy (harissa instead of hot honey)', 0.00, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_LF_001_REMOVE', 'ITEM_LF_001', 'Remove Items', 'multiple', 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_REMOVE_CHEESE', 'CG_LF_001_REMOVE', 'No cheese', 0.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_REMOVE_GARLIC', 'CG_LF_001_REMOVE', 'No garlic', 0.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_REMOVE_SALAD', 'CG_LF_001_REMOVE', 'No salad (fries only)', 0.00, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_REMOVE_HONEY', 'CG_LF_001_REMOVE', 'No hot honey', 0.00, 0, 4);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_LF_001_ADDON', 'ITEM_LF_001', 'Add-ons', 'multiple', 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_ADDON_CHICKEN', 'CG_LF_001_ADDON', 'Chicken topping on fries', 3.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_ADDON_BRISKET', 'CG_LF_001_ADDON', 'Brisket topping on fries', 4.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_ADDON_MIXED', 'CG_LF_001_ADDON', 'Mixed topping on fries', 5.00, 0, 3);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_LF_001_EXTRA', 'ITEM_LF_001', 'Extras', 'multiple', 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_EXTRA_HALLOUMI', 'CG_LF_001_EXTRA', 'Grilled Halloumi Sticks', 6.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_EXTRA_POPPERS', 'CG_LF_001_EXTRA', 'Cheesy Pizza Poppers', 6.50, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_LF_001_DRINK', 'ITEM_LF_001', 'Add a Drink', 'single', 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_DRINK_1', 'CG_LF_001_DRINK', 'Shani Can 330ml', 2.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_DRINK_2', 'CG_LF_001_DRINK', 'Rubicon Guava Can 330ml', 2.50, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_DRINK_3', 'CG_LF_001_DRINK', 'Rubicon Mango Can 330ml', 2.50, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_DRINK_4', 'CG_LF_001_DRINK', 'Rubicon Passion Fruit Can 330ml', 2.50, 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_DRINK_5', 'CG_LF_001_DRINK', 'Palestine Cola Can 330ml', 2.50, 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_DRINK_6', 'CG_LF_001_DRINK', 'Palestine Cola (Sugar Free) Can 330ml', 2.50, 0, 6);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_DRINK_7', 'CG_LF_001_DRINK', 'Palestine Lemon and Lime Can 330ml', 2.50, 0, 7);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_DRINK_8', 'CG_LF_001_DRINK', 'Palestine Orange Can 330ml', 2.50, 0, 8);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_DRINK_9', 'CG_LF_001_DRINK', 'Bottled Water 350ml', 2.50, 0, 9);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_001_DRINK_10', 'CG_LF_001_DRINK', 'Capri Sun 350ml', 2.00, 0, 10);

-- Customizations for ITEM_LF_002
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_LF_002_SPICE', 'ITEM_LF_002', 'Spice Level', 'single', 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_SPICE_MILD', 'CG_LF_002_SPICE', 'Mild', 0.00, 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_SPICE_SPICY', 'CG_LF_002_SPICE', 'Spicy (harissa instead of hot honey)', 0.00, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_LF_002_REMOVE', 'ITEM_LF_002', 'Remove Items', 'multiple', 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_REMOVE_CHEESE', 'CG_LF_002_REMOVE', 'No cheese', 0.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_REMOVE_GARLIC', 'CG_LF_002_REMOVE', 'No garlic', 0.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_REMOVE_SALAD', 'CG_LF_002_REMOVE', 'No salad (fries only)', 0.00, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_REMOVE_HONEY', 'CG_LF_002_REMOVE', 'No hot honey', 0.00, 0, 4);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_LF_002_ADDON', 'ITEM_LF_002', 'Add-ons', 'multiple', 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_ADDON_CHICKEN', 'CG_LF_002_ADDON', 'Chicken topping on fries', 3.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_ADDON_BRISKET', 'CG_LF_002_ADDON', 'Brisket topping on fries', 4.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_ADDON_MIXED', 'CG_LF_002_ADDON', 'Mixed topping on fries', 5.00, 0, 3);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_LF_002_EXTRA', 'ITEM_LF_002', 'Extras', 'multiple', 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_EXTRA_HALLOUMI', 'CG_LF_002_EXTRA', 'Grilled Halloumi Sticks', 6.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_EXTRA_POPPERS', 'CG_LF_002_EXTRA', 'Cheesy Pizza Poppers', 6.50, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_LF_002_DRINK', 'ITEM_LF_002', 'Add a Drink', 'single', 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_DRINK_1', 'CG_LF_002_DRINK', 'Shani Can 330ml', 2.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_DRINK_2', 'CG_LF_002_DRINK', 'Rubicon Guava Can 330ml', 2.50, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_DRINK_3', 'CG_LF_002_DRINK', 'Rubicon Mango Can 330ml', 2.50, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_DRINK_4', 'CG_LF_002_DRINK', 'Rubicon Passion Fruit Can 330ml', 2.50, 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_DRINK_5', 'CG_LF_002_DRINK', 'Palestine Cola Can 330ml', 2.50, 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_DRINK_6', 'CG_LF_002_DRINK', 'Palestine Cola (Sugar Free) Can 330ml', 2.50, 0, 6);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_DRINK_7', 'CG_LF_002_DRINK', 'Palestine Lemon and Lime Can 330ml', 2.50, 0, 7);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_DRINK_8', 'CG_LF_002_DRINK', 'Palestine Orange Can 330ml', 2.50, 0, 8);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_DRINK_9', 'CG_LF_002_DRINK', 'Bottled Water 350ml', 2.50, 0, 9);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_002_DRINK_10', 'CG_LF_002_DRINK', 'Capri Sun 350ml', 2.00, 0, 10);

-- Customizations for ITEM_LF_003
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_LF_003_SPICE', 'ITEM_LF_003', 'Spice Level', 'single', 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_SPICE_MILD', 'CG_LF_003_SPICE', 'Mild', 0.00, 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_SPICE_SPICY', 'CG_LF_003_SPICE', 'Spicy (harissa instead of hot honey)', 0.00, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_LF_003_REMOVE', 'ITEM_LF_003', 'Remove Items', 'multiple', 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_REMOVE_CHEESE', 'CG_LF_003_REMOVE', 'No cheese', 0.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_REMOVE_GARLIC', 'CG_LF_003_REMOVE', 'No garlic', 0.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_REMOVE_SALAD', 'CG_LF_003_REMOVE', 'No salad (fries only)', 0.00, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_REMOVE_HONEY', 'CG_LF_003_REMOVE', 'No hot honey', 0.00, 0, 4);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_LF_003_ADDON', 'ITEM_LF_003', 'Add-ons', 'multiple', 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_ADDON_CHICKEN', 'CG_LF_003_ADDON', 'Chicken topping on fries', 3.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_ADDON_BRISKET', 'CG_LF_003_ADDON', 'Brisket topping on fries', 4.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_ADDON_MIXED', 'CG_LF_003_ADDON', 'Mixed topping on fries', 5.00, 0, 3);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_LF_003_EXTRA', 'ITEM_LF_003', 'Extras', 'multiple', 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_EXTRA_HALLOUMI', 'CG_LF_003_EXTRA', 'Grilled Halloumi Sticks', 6.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_EXTRA_POPPERS', 'CG_LF_003_EXTRA', 'Cheesy Pizza Poppers', 6.50, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_LF_003_DRINK', 'ITEM_LF_003', 'Add a Drink', 'single', 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_DRINK_1', 'CG_LF_003_DRINK', 'Shani Can 330ml', 2.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_DRINK_2', 'CG_LF_003_DRINK', 'Rubicon Guava Can 330ml', 2.50, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_DRINK_3', 'CG_LF_003_DRINK', 'Rubicon Mango Can 330ml', 2.50, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_DRINK_4', 'CG_LF_003_DRINK', 'Rubicon Passion Fruit Can 330ml', 2.50, 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_DRINK_5', 'CG_LF_003_DRINK', 'Palestine Cola Can 330ml', 2.50, 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_DRINK_6', 'CG_LF_003_DRINK', 'Palestine Cola (Sugar Free) Can 330ml', 2.50, 0, 6);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_DRINK_7', 'CG_LF_003_DRINK', 'Palestine Lemon and Lime Can 330ml', 2.50, 0, 7);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_DRINK_8', 'CG_LF_003_DRINK', 'Palestine Orange Can 330ml', 2.50, 0, 8);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_DRINK_9', 'CG_LF_003_DRINK', 'Bottled Water 350ml', 2.50, 0, 9);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_LF_003_DRINK_10', 'CG_LF_003_DRINK', 'Capri Sun 350ml', 2.00, 0, 10);

-- Customizations for ITEM_RB_001
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_RB_001_SPICE', 'ITEM_RB_001', 'Spice Level', 'single', 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_SPICE_MILD', 'CG_RB_001_SPICE', 'Mild', 0.00, 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_SPICE_SPICY', 'CG_RB_001_SPICE', 'Spicy (harissa instead of hot honey)', 0.00, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_RB_001_REMOVE', 'ITEM_RB_001', 'Remove Items', 'multiple', 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_REMOVE_CHEESE', 'CG_RB_001_REMOVE', 'No cheese', 0.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_REMOVE_GARLIC', 'CG_RB_001_REMOVE', 'No garlic', 0.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_REMOVE_SALAD', 'CG_RB_001_REMOVE', 'No salad (fries only)', 0.00, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_REMOVE_HONEY', 'CG_RB_001_REMOVE', 'No hot honey', 0.00, 0, 4);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_RB_001_ADDON', 'ITEM_RB_001', 'Add-ons', 'multiple', 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_ADDON_CHICKEN', 'CG_RB_001_ADDON', 'Chicken topping on fries', 3.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_ADDON_BRISKET', 'CG_RB_001_ADDON', 'Brisket topping on fries', 4.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_ADDON_MIXED', 'CG_RB_001_ADDON', 'Mixed topping on fries', 5.00, 0, 3);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_RB_001_EXTRA', 'ITEM_RB_001', 'Extras', 'multiple', 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_EXTRA_HALLOUMI', 'CG_RB_001_EXTRA', 'Grilled Halloumi Sticks', 6.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_EXTRA_POPPERS', 'CG_RB_001_EXTRA', 'Cheesy Pizza Poppers', 6.50, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_RB_001_DRINK', 'ITEM_RB_001', 'Add a Drink', 'single', 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_DRINK_1', 'CG_RB_001_DRINK', 'Shani Can 330ml', 2.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_DRINK_2', 'CG_RB_001_DRINK', 'Rubicon Guava Can 330ml', 2.50, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_DRINK_3', 'CG_RB_001_DRINK', 'Rubicon Mango Can 330ml', 2.50, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_DRINK_4', 'CG_RB_001_DRINK', 'Rubicon Passion Fruit Can 330ml', 2.50, 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_DRINK_5', 'CG_RB_001_DRINK', 'Palestine Cola Can 330ml', 2.50, 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_DRINK_6', 'CG_RB_001_DRINK', 'Palestine Cola (Sugar Free) Can 330ml', 2.50, 0, 6);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_DRINK_7', 'CG_RB_001_DRINK', 'Palestine Lemon and Lime Can 330ml', 2.50, 0, 7);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_DRINK_8', 'CG_RB_001_DRINK', 'Palestine Orange Can 330ml', 2.50, 0, 8);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_DRINK_9', 'CG_RB_001_DRINK', 'Bottled Water 350ml', 2.50, 0, 9);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_001_DRINK_10', 'CG_RB_001_DRINK', 'Capri Sun 350ml', 2.00, 0, 10);

-- Customizations for ITEM_RB_002
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_RB_002_SPICE', 'ITEM_RB_002', 'Spice Level', 'single', 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_SPICE_MILD', 'CG_RB_002_SPICE', 'Mild', 0.00, 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_SPICE_SPICY', 'CG_RB_002_SPICE', 'Spicy (harissa instead of hot honey)', 0.00, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_RB_002_REMOVE', 'ITEM_RB_002', 'Remove Items', 'multiple', 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_REMOVE_CHEESE', 'CG_RB_002_REMOVE', 'No cheese', 0.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_REMOVE_GARLIC', 'CG_RB_002_REMOVE', 'No garlic', 0.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_REMOVE_SALAD', 'CG_RB_002_REMOVE', 'No salad (fries only)', 0.00, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_REMOVE_HONEY', 'CG_RB_002_REMOVE', 'No hot honey', 0.00, 0, 4);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_RB_002_ADDON', 'ITEM_RB_002', 'Add-ons', 'multiple', 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_ADDON_CHICKEN', 'CG_RB_002_ADDON', 'Chicken topping on fries', 3.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_ADDON_BRISKET', 'CG_RB_002_ADDON', 'Brisket topping on fries', 4.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_ADDON_MIXED', 'CG_RB_002_ADDON', 'Mixed topping on fries', 5.00, 0, 3);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_RB_002_EXTRA', 'ITEM_RB_002', 'Extras', 'multiple', 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_EXTRA_HALLOUMI', 'CG_RB_002_EXTRA', 'Grilled Halloumi Sticks', 6.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_EXTRA_POPPERS', 'CG_RB_002_EXTRA', 'Cheesy Pizza Poppers', 6.50, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_RB_002_DRINK', 'ITEM_RB_002', 'Add a Drink', 'single', 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_DRINK_1', 'CG_RB_002_DRINK', 'Shani Can 330ml', 2.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_DRINK_2', 'CG_RB_002_DRINK', 'Rubicon Guava Can 330ml', 2.50, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_DRINK_3', 'CG_RB_002_DRINK', 'Rubicon Mango Can 330ml', 2.50, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_DRINK_4', 'CG_RB_002_DRINK', 'Rubicon Passion Fruit Can 330ml', 2.50, 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_DRINK_5', 'CG_RB_002_DRINK', 'Palestine Cola Can 330ml', 2.50, 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_DRINK_6', 'CG_RB_002_DRINK', 'Palestine Cola (Sugar Free) Can 330ml', 2.50, 0, 6);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_DRINK_7', 'CG_RB_002_DRINK', 'Palestine Lemon and Lime Can 330ml', 2.50, 0, 7);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_DRINK_8', 'CG_RB_002_DRINK', 'Palestine Orange Can 330ml', 2.50, 0, 8);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_DRINK_9', 'CG_RB_002_DRINK', 'Bottled Water 350ml', 2.50, 0, 9);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_002_DRINK_10', 'CG_RB_002_DRINK', 'Capri Sun 350ml', 2.00, 0, 10);

-- Customizations for ITEM_RB_003
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_RB_003_SPICE', 'ITEM_RB_003', 'Spice Level', 'single', 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_SPICE_MILD', 'CG_RB_003_SPICE', 'Mild', 0.00, 1, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_SPICE_SPICY', 'CG_RB_003_SPICE', 'Spicy (harissa instead of hot honey)', 0.00, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_RB_003_REMOVE', 'ITEM_RB_003', 'Remove Items', 'multiple', 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_REMOVE_CHEESE', 'CG_RB_003_REMOVE', 'No cheese', 0.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_REMOVE_GARLIC', 'CG_RB_003_REMOVE', 'No garlic', 0.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_REMOVE_SALAD', 'CG_RB_003_REMOVE', 'No salad (fries only)', 0.00, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_REMOVE_HONEY', 'CG_RB_003_REMOVE', 'No hot honey', 0.00, 0, 4);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_RB_003_ADDON', 'ITEM_RB_003', 'Add-ons', 'multiple', 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_ADDON_CHICKEN', 'CG_RB_003_ADDON', 'Chicken topping on fries', 3.00, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_ADDON_BRISKET', 'CG_RB_003_ADDON', 'Brisket topping on fries', 4.00, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_ADDON_MIXED', 'CG_RB_003_ADDON', 'Mixed topping on fries', 5.00, 0, 3);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_RB_003_EXTRA', 'ITEM_RB_003', 'Extras', 'multiple', 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_EXTRA_HALLOUMI', 'CG_RB_003_EXTRA', 'Grilled Halloumi Sticks', 6.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_EXTRA_POPPERS', 'CG_RB_003_EXTRA', 'Cheesy Pizza Poppers', 6.50, 0, 2);
INSERT INTO customization_groups (group_id, item_id, name, type, is_required, sort_order) VALUES ('CG_RB_003_DRINK', 'ITEM_RB_003', 'Add a Drink', 'single', 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_DRINK_1', 'CG_RB_003_DRINK', 'Shani Can 330ml', 2.50, 0, 1);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_DRINK_2', 'CG_RB_003_DRINK', 'Rubicon Guava Can 330ml', 2.50, 0, 2);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_DRINK_3', 'CG_RB_003_DRINK', 'Rubicon Mango Can 330ml', 2.50, 0, 3);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_DRINK_4', 'CG_RB_003_DRINK', 'Rubicon Passion Fruit Can 330ml', 2.50, 0, 4);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_DRINK_5', 'CG_RB_003_DRINK', 'Palestine Cola Can 330ml', 2.50, 0, 5);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_DRINK_6', 'CG_RB_003_DRINK', 'Palestine Cola (Sugar Free) Can 330ml', 2.50, 0, 6);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_DRINK_7', 'CG_RB_003_DRINK', 'Palestine Lemon and Lime Can 330ml', 2.50, 0, 7);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_DRINK_8', 'CG_RB_003_DRINK', 'Palestine Orange Can 330ml', 2.50, 0, 8);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_DRINK_9', 'CG_RB_003_DRINK', 'Bottled Water 350ml', 2.50, 0, 9);
INSERT INTO customization_options (option_id, group_id, name, additional_price, is_default, sort_order) VALUES ('CO_RB_003_DRINK_10', 'CG_RB_003_DRINK', 'Capri Sun 350ml', 2.00, 0, 10);
